"""
BioVault Decoder
Converts DNA base sequences → original binary data, with checksum verification.
"""

import re
from typing import List, Tuple, Optional
from .encoder import DNAFragment, BITS_MAP, fragment_checksum


class DecodeError(Exception):
    pass


class ChecksumError(DecodeError):
    pass


def dna_to_bits(seq: str) -> str:
    return "".join(BITS_MAP[base] for base in seq)


def bits_to_bytes(bits: str, original_length: int) -> bytes:
    # Trim to actual byte boundary
    byte_count = original_length
    usable_bits = bits[: byte_count * 8]
    return bytes(int(usable_bits[i : i + 8], 2) for i in range(0, len(usable_bits), 8))


def decode_fragment(fragment: DNAFragment, verify: bool = True) -> bytes:
    """Decode a single DNAFragment back to bytes."""
    bits = dna_to_bits(fragment.sequence)
    data = bits_to_bytes(bits, fragment.original_length)

    if verify:
        expected = fragment_checksum(data)
        if expected != fragment.checksum:
            raise ChecksumError(
                f"Fragment {fragment.index}: checksum mismatch "
                f"(expected {fragment.checksum}, got {expected})"
            )

    return data


def decode(fragments: List[DNAFragment], verify: bool = True) -> Tuple[bytes, List[int]]:
    """
    Decode a list of DNA fragments back to the original bytes.

    Args:
        fragments: List of DNAFragment objects (order doesn't matter, sorted by index)
        verify: Whether to verify checksums

    Returns:
        (decoded_bytes, list_of_failed_indices)
    """
    # Sort by index to reconstruct order
    sorted_fragments = sorted(fragments, key=lambda f: f.index)

    result = bytearray()
    failed = []

    for frag in sorted_fragments:
        try:
            chunk = decode_fragment(frag, verify=verify)
            result.extend(chunk)
        except (ChecksumError, KeyError, ValueError) as e:
            print(f"[WARN] {e}")
            failed.append(frag.index)
            # Fill with zeros for failed fragments (ECC can patch later)
            result.extend(bytes(frag.original_length))

    return bytes(result), failed


def parse_fasta(fasta_text: str) -> List[DNAFragment]:
    """
    Parse a FASTA file generated by BioVault back into DNAFragment objects.
    """
    fragments = []
    # Match header lines like: >fragment_000001|len=75|chk=abc12345
    pattern = re.compile(
        r">fragment_(\d+)\|len=(\d+)\|chk=([a-f0-9]+)\n([ATCG]+)", re.MULTILINE
    )

    for match in pattern.finditer(fasta_text):
        idx = int(match.group(1))
        length = int(match.group(2))
        chk = match.group(3)
        seq = match.group(4)

        fragments.append(
            DNAFragment(
                index=idx,
                sequence=seq,
                checksum=chk,
                original_length=length,
            )
        )

    if not fragments:
        raise DecodeError("No valid BioVault fragments found in FASTA input.")

    return fragments


def simulate_sequencing_errors(
    fragments: List[DNAFragment], error_rate: float = 0.01
) -> List[DNAFragment]:
    """
    Simulate real-world sequencing read errors for testing ECC.
    Introduces random substitutions at the given rate.
    """
    import random

    bases = list("ATCG")
    noisy = []

    for frag in fragments:
        seq = list(frag.sequence)
        for i in range(len(seq)):
            if random.random() < error_rate:
                seq[i] = random.choice([b for b in bases if b != seq[i]])
        noisy.append(
            DNAFragment(
                index=frag.index,
                sequence="".join(seq),
                checksum=frag.checksum,
                original_length=frag.original_length,
            )
        )

    return noisy
